version: '3.7'

services:
  trainy_front:
    image: trainy_front:dev
    container_name: trainy_front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'